### ISSUE TITLE
Some packages have circles, not sure why

### ISSUE THREAD

**Issue by gauravve** [loov/goda#33]
This is more of a question that an issue. Not sure why I am seeing circles in the some packages.

Not able to upload an image here but here is some ascii art with an emoticon. 

cmd ---> ⭕️ --> router

**Comment by egonelbre** [comment]
Sorry, for the late reply. It's an artifact of using `graphviz` and `-cluster` mode.

The circle signifies the "module package", where other things might be nested. Since graphviz doesn't allow to draw an arrow from a node to a group (at least easily), it's easier to insert a "pseudo circle" signifying the package.
